name: Release workflow

on:
  push:
    tags:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn test -B

  deliver-jar:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build the JAR file with Maven
        run: mvn package -B
      - name: Upload the JAR file to GitHub as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: zipped-project-jar-file
          path: target/*.jar

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: deliver-jar
    steps:
      - name: Get artifact
        uses: actions/download-artifact@4
        with:
          name: zipped-project-jar-file
          path: build
      - name: Realease the jar on github
        uses: ncipollo/release-action@1
        with:
          artifacts: "build/*.jar"

